name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-20.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/zi00duck/Hydra_Begonia
          kernel-branch: 13.x
          config: defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 13
          aosp-clang-version: r450784d
		  anykernel3: true
		  anykernel3-url: https://github.com/osm0sis/AnyKernel3
